name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@8b5843768416150660d577c7d4659db2aa865559
    permissions:
      contents: write
    with:
      modules: >-
        [
          "version"
        ]
        
      zip_command: >
        cp res/Koaloader.json artifacts/Koaloader.json
        cd artifacts
        zip ../$ZIP_NAME ./* -r