name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@4570a195a1222e728b2a643cc53164b49549a371
    permissions:
      contents: write
    with:
      modules: >-
        [
          "audioses",
          "d3d9",
          "d3d10",
          "d3d11",
          "dinput8",
          "dwmapi",
          "dxgi",
          "glu32",
          "hid",
          "iphlpapi",
          "msasn1",
          "msimg32",
          "mswsock",
          "opengl32",
          "profapi",
          "propsys",
          "textshaping",
          "version",
          "winhttp",
          "wldp",
          "winmm",
          "xinput9_1_0"
        ]
        
      zip_command: >
        cp res/Koaloader.json artifacts/Koaloader.json &&
        cd artifacts &&
        zip ../$ZIP_NAME ./* -r

      config: Release
