name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@6d72f1af04406f3c20f85cf64de0cb2c4e7686d9
    permissions:
      contents: write
    with:
      modules: >-
        [
          "version"
        ]
        

      cmake_options: -DPROXY_DLL=$MODULE

      zip_command: >
        cp res/Koaloader.json artifacts/Koaloader.json
        cd artifacts
        zip ../$ZIP_NAME ./* -r